[]{#fundamentals}

# Keemia alused

## Sissejuhatus

### Õpitulemused

\begin{multicols}{2}

Kursuse lõpus õpilane:

1. valdab ettekujutust keemia ajaloolisest arengust;

2. eristab kvalitatiivset ja kvantitatiivset analüüsi ning füüsikalisi ja keemilisi uurimismeetodeid.

\end{multicols}

### Õppesisu

Keemia kui teaduse kujunemine. Füüsikalised ja keemilised uurimismeetodid keemias. Keemiaga seotud karjäärivalikud.

### Põhimõisted

keemiline analüüs
: avastamine, millised elemendid on omavahel ühinenud, moodustades aine[@atkins_2010_chemical(lk F22)]

kvalitatiivne analüüs
: valimis sisalduvate ainete identifitseerimine[@atkins_2010_chemical(lk F69)]

kvantitatiivne analüüs
: iga esineva aine või elemendi koguse määramine[@atkins_2010_chemical(lk F69)]

keemiline süntees
: elementide ühendamise protsess ühendite saamiseks või ühe ühendi teisendamine teiseks[@atkins_2010_chemical(lk F22)]

### Praktilised tööd ja IKT rakendamine

Õppekäik keemiaga seotud ettevõttesse, õppeasutusse vms.

## Aine ehitus

### Õpitulemused

\begin{multicols}{2}

Kursuse lõpus õpilane:

1. kirjeldab elektronide paiknemist aatomi välises elektronkihis (üksikud elektronid, elektronipaarid) sõltuvalt elemendi asukohast perioodilisustabelis (A-rühmade elementide korral);

2. selgitab A-rühmade elementide metallilisuse ja mittemetallilisuse muutumist perioodilisustabelis seoses aatomi ehituse muutumisega; 

3. määrab A-rühmade keemiliste elementide maksimaalseid ja minimaalseid oksüdatsiooniastmeid elemendi asukoha järgi perioodilisustabelis ning koostab elementide tüüpühendite valemeid;

4. selgitab tüüpiliste näidete varal kovalentse, ioonilise, metallilise ja vesiniksideme olemust; 

5. hindab kovalentse sideme polaarsust, lähtudes sidet moodustavate elementide asukohast perioodilisustabelis; 

6. kirjeldab ning hindab keemiliste sidemete ja molekulide vastastiktoime (ka vesiniksideme) mõju ainete omadustele.

\end{multicols}

### Õppesisu

\begin{multicols}{2}

1. Tänapäevane ettekujutus aatomi ehitusest. 

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

3. Keemilise sideme liigid.

4. Vesinikside.

5. Molekulidevahelised jõud.

6. Ainete füüsikaliste omaduste sõltuvus aine ehitusest. 

\end{multicols}

### Põhimõisted

aatomorbitaal
:

mittepolaarne kovalentne side
:

polaarne kovalentne side
:

osalaeng
:

vesinikside
:

### Praktilised tööd ja IKT rakendamine

Lihtsamate molekulide struktuuri uurimine ja võrdlemine molekulimudelite või arvutiprogrammidega.

## Miks ja kuidas toimuvad keemilised reaktsioonid 

### Õpitulemused

\begin{multicols}{2}

Kursuse lõpus õpilane:

1. seostab keemilist reaktsiooni aineosakeste üleminekuga püsivamasse olekusse;

2. selgitab keemiliste reaktsioonide soojusefekte, lähtudes keemiliste sidemete tekkimisel ja lagunemisel esinevatest energiamuutustest;

3. analüüsib keemilise reaktsiooni kiirust mõjutavate tegurite toimet ning selgitab keemiliste protsesside kiiruse muutmist argielus;

4. mõistab, et pöörduvate reaktsioonide puhul tekib vastassuunas kulgevate protsesside vahel tasakaal, ning toob sellekohaseid näiteid argielust ja tehnoloogiast.

\end{multicols}

### Õppesisu

\begin{multicols}{2}

1. Keemilise reaktsiooni aktiveerimisenergia, aktiivsed põrked. 

2. Ekso- ja endotermilised reaktsioonid.

3. Keemilise reaktsiooni kiirus, seda mõjutavad tegurid.

4. Keemiline tasakaal ja selle nihkumine (Le Chatelier’ printsiibist tutvustavalt). 

\end{multicols}

### Põhimõisted

reaktsiooni aktiveerimisenergia
:

reaktsiooni soojusefekt
:

reaktsiooni kiirus
:

katalüsaator 
: aine, mis suurendab reaktsiooni kiirust, kuid mida ise reaktsiooni käigus ei tarbita[@atkins_2010_chemical(lk F61)]

katalüüs
:

pöörduv reaktsioon
:

pöördumatu reaktsioon
:

keemiline tasakaal
: olukord, mida modelleeritakse keemilise võrrandiga, mis sümboliseerib nii kvalitatiivseid kui ka kvantitatiivseid muutusi, mis toimuvad keemilises reaktsioonis[@atkins_2010_chemical(lk 62)]


### Praktilised tööd ja IKT rakendamine

\begin{multicols}{2}

1. Keemilise reaktsiooni kiirust mõjutavate tegurite toime uurimine;

2. keemilise reaktsiooni soojusefekti uurimine;

3. auto heitgaaside katalüsaatori tööpõhimõtte selgitamine internetimaterjalide põhjal;

4. keemilise tasakaalu nihkumise uurimine sh arvutimudeli abil.

\end{multicols}

## Lahustumisprotsess, keemilised reaktsioonid lahustes

### Õpitulemused

\begin{multicols}{2}

Kursuse lõpus õpilane:

1. kirjeldab lahuste teket (iooniliste ja kovalentsete ainete korral);

2. eristab elektrolüüte ja mitteelektrolüüte ning tugevaid ja nõrku elektrolüüte;

3. selgitab happe ja aluse mõistet protolüütilise teoora põhjal;

4. oskab arvutada molaarset kontsentratsiooni;

5. koostab ioonidevaheliste reaktsioonide võrrandeid (molekulaarsel ja ioonsel kujul);

6. hindab ning põhjendab ainete vees lahustumise korral lahuses tekkivat keskkonda.

\end{multicols}

### Õppesisu 

\begin{multicols}{2}

1. Ainete lahustumisprotsess.

2. Elektrolüüdid ja mitteelektrolüüdid; tugevad ja nõrgad elektrolüüdid.

3. Hapete ja aluste protolüütiline teooria. ; 

4. Molaarne kontsentratsioon (tutvustavalt).

5. Ioonidevahelised reaktsioonid lahustes, nende kulgemise tingimused.

6. pH. 

7. Keskkond hüdrolüüsuva soola lahuses. 

\end{multicols}

### Põhimõisted

hüdraatumine
:

elektrolüüt
: aine, mis lahuses esineb ioonidena[@atkins_2010_chemical(lk F66)]

mitteelektrolüüt
: aine, mis lahuses ioone ei moodusta[@atkins_2010_chemical(lk F66)]

tugev elektrolüüt
:     aine, mis esineb lahuses peaaegu täielikult ioonidena[@atkins_2010_chemical(lk F66)]

nõrk elektrolüüt
: lahuses mittetäielikult ioniseeritud aine[@atkins_2010_chemical(lk F66)]

hape
: molekul või ioon, mis on prootoni doonor[@atkins_2010_chemical(lk F74)]

alus
: molekul või ioon, mis on prootoni aktseptor[@atkins_2010_chemical(lk F74)]

molaarne kontsentratsioon
: lahustunud aine molekulide või valemiühikute kogus (moolides) antud lahuse mahus (liitrites) (avaldis \@ref(eq:amount-concentration) leheküljel `r render_pageref(reference="eq:amount-concentration")`)[@atkins_2010_chemical(lk F54)]

soola hüdrolüüs
:

### Praktilised tööd ja IKT rakendamine

\begin{multicols}{2}

1. Lahustumise soojusefektide uurimine;

2. erinevate lahuste elektrijuhtivuse võrdlemine (pirni heleduse või Vernier’ anduriga);

3. nõrkade ja tugevate hapete ning aluste pH ja elektrijuhtivuse võrdlemine;

4. ioonidevaheliste reaktsioonide toimumise uurimine;

5. erinevate ainete vesilahuste keskkonna (lahuste pH) uurimine;

6. lahuse kontsentratsiooni määramine tiitrimisel (nt vee mööduva kareduse määramine, leelise kontsentratsiooni määramine puhastusvahendis või happe kontsentratsiooni määramine akuhappes vms).

\end{multicols}

## Õpiku seotud osad

1.1 The Nuclear Model of the Atom, 1-3
1.9 Atomic Orbitals, 23-29
1.17 Ionization Energy, 42-44

CHEMICAL BONDS, 55-91, 16

3.11 Bonding in Heteronuclear Diatomic Molecules, 120-121

5.2 Ion–Dipole Forces, 172-173
5.5 Hydrogen Bonding, 178-179

 7.4 Heat, 243

 10.5 The Direction of Reaction, 396-394
 THE RESPONSE OF EQUILIBRIA TO CHANGES IN CONDITIONS 405-414

 11.5 The pH Scale, 431-434
 POLYPROTIC ACIDS AND BASES, 454-464
 AUTOPROTOLYSIS AND pH, 464-468

12.14 Qualitative Analysis, 507-508

13.3 The Structure of Galvanic Cells, 522-524

REACTION RATES, 561-571
14.8 The Rate Laws of Elementary Reactions, 581-585
14.10 Rates and Equilibrium, 586-587
14.11 The Effect of Temperature, 14.12 Collision Theory, 587-594
ACCELERATING REACTIONS, 595-610

15.4 Compounds of Hydrogen, 618-619
15.16 Compounds with Hydrogen and the Halogens, 642-644

## Kalender

### 2023-12-07

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava:

1. Sissejuhatus.

2. Eelnevalt õpitu kordamine: tutvustus ja orienteerumine, aine ja energia[@atkins_2010_chemical(lk F1-F13)]. Valemini 3 jõudsin rääkida.

### 2023-12-12

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava:

3. Eelnevalt õpitu kordamine: elemendid ja aatomid[@atkins_2010_chemical(lk F15-F21)]. Rääkisin prootonite arvu Z'ni.

### 2023-12-12

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava:

3. Eelnevalt õpitu kordamine: elemendid ja aatomid[@atkins_2010_chemical(lk F15-F21)]. Käsitlesime isotoobid.

### 2023-12-14

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Põhimõisted:

keemiline analüüs
: avastamine, millised elemendid on omavahel ühinenud, moodustades aine[@atkins_2010_chemical(lk F22)]

keemiline süntees
: elementide ühendamise protsess ühendite saamiseks või ühe ühendi teisendamine teiseks[@atkins_2010_chemical(lk F22)]

Kava:

3. Eelnevalt õpitu kordamine: elemendid ja aatomid[@atkins_2010_chemical(lk F15-F21)]. Alustasime elementide organisatsiooniga.

4. Eelnevalt õpitu kordamine: ühendid[@atkins_2010_chemical(lk F22-F28)]. Ühendite üldosa käsitlesime.

### 2023-12-14

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava:

4. Eelnevalt õpitu kordamine: ühendid[@atkins_2010_chemical(lk F22-F28)]. Ioonilised ühendid käsitlesime kuni näiteni C.2.

### 2023-12-14

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava:

5. Eelnevalt õpitu kordamine: ühendite nomenklatuur[@atkins_2010_chemical(lk F29-F36)]. Jõudsin rääkida katioonide nimetuste esimese lõigu.

### 2023-12-19

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava:

5. Eelnevalt õpitu kordamine: ühendite nomenklatuur[@atkins_2010_chemical(lk F29-F36)]. Enesetest D.3A tehtud.

6. Eelnevalt õpitu kordamine: Moolid ja molaarmassid[@atkins_2010_chemical(lk F37-F43)].

### 2024-1-9

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava: Eelnevalt õpitu kordamine: Moolid ja molaarmassid. Mool[@atkins_2010_chemical(lk F37-F39)].

### 2024-1-9

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

4. Molaarne kontsentratsioon (tutvustavalt).

Õpitulemusena õpilane

4. oskab arvutada molaarset kontsentratsiooni.

Põhimõiste:

molaarne kontsentratsioon
: lahustunud aine molekulide või valemiühikute kogus (moolides) antud lahuse mahus (liitrites) (avaldis \@ref(eq:amount-concentration) leheküljel `r render_pageref(reference="eq:amount-concentration")`)[@atkins_2010_chemical(lk F54)]

Kava: Eelnevalt õpitu kordamine: Moolid ja molaarmassid. Molaarmass[@atkins_2010_chemical(lk F39-F43)].

### 2024-1-11

Õpilased ei osalenud.

### 2024-1-11

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

4. Molaarne kontsentratsioon (tutvustavalt).

Õpitulemusena õpilane

4. oskab arvutada molaarset kontsentratsiooni.

Põhimõiste:

molaarne kontsentratsioon
: lahustunud aine molekulide või valemiühikute kogus (moolides) antud lahuse mahus (liitrites) (avaldis \@ref(eq:amount-concentration) leheküljel `r render_pageref(reference="eq:amount-concentration")`)[@atkins_2010_chemical(lk F54)]

Kava: 	Kordamine: mooli ja molaarmassi test ja ülevaatamine.

### 2024-1-11

Kursuse lõpus õpilane:

3. määrab A-rühmade keemiliste elementide maksimaalseid ja minimaalseid oksüdatsiooniastmeid elemendi asukoha järgi perioodilisustabelis ning koostab elementide tüüpühendite valemeid.

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava: Eelnevalt õpitu kordamine: Keemiliste valemite määramine[@atkins_2010_chemical(lk F45-F50)].

### 2024-1-16

Kursuse lõpus õpilane:

3. määrab A-rühmade keemiliste elementide maksimaalseid ja minimaalseid oksüdatsiooniastmeid elemendi asukoha järgi perioodilisustabelis ning koostab elementide tüüpühendite valemeid.

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava: Eelnevalt õpitu kordamine: Keemiliste valemite määramine[@atkins_2010_chemical(lk F45-F50)]. Ühendi komponentide massi osamäärade arvutamise ülesannete lahendamise selgitamine.

### 2024-1-16

Õppesisu:

1. Ainete lahustumisprotsess.

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava: Eelnevalt õpitu kordamine:

1. Keemiliste valemite määramine[@atkins_2010_chemical(lk F45-F50)]. Massi osamäärade järgi empiirilise valemi tuletamise ülesande lahendamise selgitamine.

2. Segud ja lahused[@atkins_2010_chemical(lk F51-F58)].

### 2024-1-18

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava: Segud ja lahused[@atkins_2010_chemical(lk F51-F58)]. Jõudsin seletama hakata [viiendat ülesannet](#intro-tasks-20240118-5).

### 2024-1-18

Kursuse lõpus õpilane:

2. eristab kvalitatiivset ja kvantitatiivset analüüsi ning füüsikalisi ja keemilisi uurimismeetodeid.

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Põhimõisted:

katalüsaator
: aine, mis suurendab reaktsiooni kiirust, kuid mida ise reaktsiooni käigus ei tarbita[@atkins_2010_chemical(lk F61)]

keemiline tasakaal
: olukord, mida modelleeritakse keemilise võrrandiga, mis sümboliseerib nii kvalitatiivseid kui ka kvantitatiivseid muutusi, mis toimuvad keemilises reaktsioonis[@atkins_2010_chemical(lk 62)]

Kava:

1. Selgitasin [viienda ülesande](#intro-tasks-20240118-5) lõpuni.

2. Tutvustasin [õppekava keemia aluste teemasid](#fundamentals).

3. Eelnevalt õpitu kordamine: Keemilised võrrandid[@atkins_2010_chemical(lk F60-F63)].

### 2024-1-18

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

2. Elektrolüüdid ja mitteelektrolüüdid; tugevad ja nõrgad elektrolüüdid.

Õpitulemustena õpilane:

1. kirjeldab lahuste teket (iooniliste ja kovalentsete ainete korral);

2. eristab elektrolüüte ja mitteelektrolüüte ning tugevaid ja nõrku elektrolüüte;

5. koostab ioonidevaheliste reaktsioonide võrrandeid (molekulaarsel ja ioonsel kujul).

Põhimõisted:

elektrolüüt
: aine, mis lahuses esineb ioonidena[@atkins_2010_chemical(lk F66)]

kvalitatiivne analüüs
: valimis sisalduvate ainete identifitseerimine[@atkins_2010_chemical(lk F69)]

kvantitatiivne analüüs
: iga esineva aine või elemendi koguse määramine[@atkins_2010_chemical(lk F69)]

mitteelektrolüüt
: aine, mis lahuses ioone ei moodusta[@atkins_2010_chemical(lk F66)]

nõrk elektrolüüt
: lahuses mittetäielikult ioniseeritud aine[@atkins_2010_chemical(lk F66)]

tugev elektrolüüt
:     aine, mis esineb lahuses peaaegu täielikult ioonidena[@atkins_2010_chemical(lk F66)]

Kava: Eelnevalt õpitu kordamine: Vesilahused ja sademine[@atkins_2010_chemical(lk F65-F70)].

### 2024-1-23

Kursuse lõpus õpilane:

2. eristab kvalitatiivset ja kvantitatiivset analüüsi ning füüsikalisi ja keemilisi uurimismeetodeid.

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Põhimõisted:

keemiline tasakaal
: olukord, mida modelleeritakse keemilise võrrandiga, mis sümboliseerib nii kvalitatiivseid kui ka kvantitatiivseid muutusi, mis toimuvad keemilises reaktsioonis[@atkins_2010_chemical(lk 62)]

Kava: Selgitasin [kaheksanda ülesande](#intro-tasks-20240123-8) lõpuni.

### 2024-1-23

Õppesisu:

3. Hapete ja aluste protolüütiline teooria.

6. pH.

Õpitulemusena õpilane:

3. selgitab happe ja aluse mõistet protolüütilise teoora põhjal;

Põhimõisted:

hape
: molekul või ioon, mis on prootoni doonor[@atkins_2010_chemical(lk 74)]

alus
: molekul või ioon, mis on prootoni aktseptor[@atkins_2010_chemical(lk 74)]

Kava: Eelnevalt õpitu kordamine: Happed ja alused[@atkins_2010_chemical(lk F72-F76)].

### 2024-1-25

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava: Eelnevalt õpitu kordamine: Redoksreaktsioonid[@atkins_2010_chemical(lk F77-F84)].

### 2024-1-25

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Kava: Eelnevalt õpitu kordamine: Reaktsiooni stöhhiomeetria[@atkins_2010_chemical(lk F85-F92)].

### 2024-1-25

Kursuse lõpus õpilane:

2. eristab kvalitatiivset ja kvantitatiivset analüüsi ning füüsikalisi ja keemilisi uurimismeetodeid.

Õppesisu:

2. Informatsioon perioodilisustabelis ja selle tõlgendamine.

Põhimõisted:

keemiline analüüs
: avastamine, millised elemendid on omavahel ühinenud, moodustades aine[@atkins_2010_chemical(lk F22)]

keemiline tasakaal
: olukord, mida modelleeritakse keemilise võrrandiga, mis sümboliseerib nii kvalitatiivseid kui ka kvantitatiivseid muutusi, mis toimuvad keemilises reaktsioonis[@atkins_2010_chemical(lk 62)]

kvalitatiivne analüüs
: valimis sisalduvate ainete identifitseerimine[@atkins_2010_chemical(lk F69)]

keemiline süntees
: elementide ühendamise protsess ühendite saamiseks või ühe ühendi teisendamine teiseks[@atkins_2010_chemical(lk F22)]

Kava: Eelnevalt õpitu kordamine: Reagentide piiramine[@atkins_2010_chemical(lk F95-F103)].
